### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mishailovic** [SebaUbuntu/Android-kernel-building#15]
```
Traceback (most recent call last):
  File "/home/gitpod/.pyenv/versions/3.8.12/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/gitpod/.pyenv/versions/3.8.12/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/gitpod/.pyenv/versions/3.8.12/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/gitpod/android-kernel-builder/build_kernel/__init__.py", line 1, in <module>
    from build_kernel.utils.device import register_devices
  File "/home/gitpod/android-kernel-builder/build_kernel/utils/device.py", line 6, in <module>
    class Device:
  File "/home/gitpod/android-kernel-builder/build_kernel/utils/device.py", line 14, in Device
    TARGET_BUILD_ARTIFACTS: list[str] = []
TypeError: 'type' object is not subscriptable
```

When trying to build kernel for vayu

**Comment by SebaUbuntu** [comment]
Use Python 3.9
